### ISSUE TITLE
bowtie2-build only generate .3.bt2 and .4.bt2 two files

### ISSUE THREAD

**Issue by cyundi** [BenLangmead/bowtie2#471]
Hi everyone, I met a problem when using bowtie2 build  to generate index for my reference database that it only generate .3.bt2 and .4.bt2 two files instead of six files, and there was no error:

Converting suffix-array elements to index image
Allocating ftab, absorbFtab
Entering Ebwt loop
Getting block 1 of 1
  No samples; assembling all-inclusive block
  Sorting block of length 2558513 for bucket 1
  (Using difference cover)
  Sorting block time: 00:00:01
Returning block of 2558514 for bucket 1
Exited Ebwt loop
fchr[A]: 0
fchr[C]: 655618
fchr[G]: 1275466
fchr[T]: 1909757
fchr[$]: 2558513
Exiting Ebwt::buildToDisk()
Returning from initFromVector
Wrote 5056533 bytes to primary EBWT file: custom_ref_genomes/43404_1#100_bin.12.orig.fa.rev.1.bt2
Wrote 10234060 bytes to secondary EBWT file: custom_ref_genomes/43404_1#100_bin.12.orig.fa.rev.2.bt2
Re-opening _in1 and _in2 as input streams
Returning from Ebwt constructor
Headers:
    len: 2558513
    bwtLen: 2558514
    sz: 639629
    bwtSz: 639629
    lineRate: 6
    offRate: 0
    offMask: 0xffffffff
    ftabChars: 10
    eftabLen: 20
    eftabSz: 80
    ftabLen: 1048577
    ftabSz: 4194308
    offsLen: 2558514
    offsSz: 10234056
    lineSz: 64
    sideSz: 64
    sideBwtSz: 48
    sideBwtLen: 192
    numSides: 13326
    numLines: 13326
    ebwtTotLen: 852864
    ebwtTotSz: 852864
    color: 0
    reverse: 1
Total time for backward call to driver() for mirror index: 00:00:01

My command is:
bowtie2-build custom_ref_genomes/*fa ref_index -offrate 4

Can anyone tell me how to fix it? Thanks!

**Comment by ch4rr0** [comment]
Hello,

We pushed a change to the `bug_fixes` branch that changes the behavior of bowtie2-build to throw an exception if it encountered any issues while persisting the BWT. Would you be willing to test out the change?

Thank you

**Comment by RaghadShu** [comment]
Hi @ch4rr0, I am not the original post writer but I am facing the same issue. 

I tested out versions 2.3.4.2 in our HPC system and I kept getting the same error stemming from not having rev index files. 
I currently have this: ```/usr/bin/bowtie2-align-s version 2.3.5.1 64-bit``` on our workstation I still cannot fully index the hg38 genome. 
This is the genome I am using (wget https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/latest/hg38.fa.gz)

I also saw on another post #385 that the threads were the issue.. So i tested out many different threads and I am still missing the rev files, which are needed for bowtie2 to run. 

I am willing to test out the change, or any other recommendations :)
